### ISSUE TITLE
App not working properly

### ISSUE THREAD

**Issue by Saltycarame1** [Saad888/AutoSynthesis#12]
Hello,
There is a problem I am facing. 
When I use 2 macros and set the time correctly the app willclick on the second macro but I would get a notification in game the this action cannot be used at this time, so obbiously my craft would fail.
I am not sure what the problem is. i tried adding more seconds to the craft time thinking it might be an issue with lag, but if it was then macro 1 wouldnt have went on smoothly. 
The other thing is that after the acraft is done it wouldnt click on the tiem again to start the craft, it would just click on the macro.
I am not sure what the problem is.

**Comment by Saad888** [comment]
Hey, can you verify that the hotkeys are set correctly, and that the cancel
/ confirm hotkeys match keybind settings in the game?

**Comment by Saltycarame1** [comment]
Yes they are.
I have tried to mess abit with the time of the macro,because I noticed it clicked the second macro befor the first one is done, so if macro 1 is actually 30 second, i added 5 more second and it worked fine now.
Also it may be because of the dalamud plugin I have. I disabled many of the plugins that give me a notification in chat. i am not sure what fixed it but I am about to try crafting again, i will update you.

**Comment by vetox20** [comment]
Just to add to this, I have experienced the same and attempted the same fix as Salty with no success. 

I use the Ishgard Resto crafting macro which requires the two hotkeys. They work when activated manually using key commands.

Adjusted times and checked with stop watch to double check the times of macros were operating correctly.  Cancel / confirm operate fine. When using one macro operates also correctly. Second macro checkbox is also verified checked.

The first macro goes off without a hitch. when time for second macro nothing happens, no error is seen on screen. If i manually select the macro in the hotbar after first macro completes it completes successfully.

I can post the macro if it helps.

**Comment by Saad888** [comment]
Sure can you please post a video or images replicating the issues?

**Comment by vetox20** [comment]
Oddly enough, now when i go to launch the application the Cancel feature is now greyed out and I cant choose the keybind anymore. Previously they were appropriately selected/displayed in authosynth to CTRL-F8 and CTRL-F9 respective (see Image 9/10 at the end)


<img width="689" alt="1" src="https://user-images.githubusercontent.com/82966157/152199296-490263c6-c5d3-4e1b-aca5-33efd5b317c9.PNG">
<img width="87" alt="2" src="https://user-images.githubusercontent.com/82966157/152199300-48b6f442-a157-438b-9d5b-cb9f208f7b44.PNG">
<img width="254" alt="3" src="https://user-images.githubusercontent.com/82966157/152199301-63b6078e-4158-440d-b811-ad9694f54a90.PNG">
<img width="249" alt="4" src="https://user-images.githubusercontent.com/82966157/152199305-9c2fccd7-038b-43a6-a138-ab8d2336ec55.PNG">
<img width="647" alt="6" src="https://user-images.githubusercontent.com/82966157/152201097-5aaef1f3-e045-4a0f-8323-29e919154e7a.PNG">
Below 2 images is macro run manually via keybinds
<img width="272" alt="7" src="https://user-images.githubusercontent.com/82966157/152199312-525c78ad-10b1-4ba5-8f05-1031cc06f3fb.PNG">
<img width="279" alt="8" src="https://user-images.githubusercontent.com/82966157/152199317-c6639197-b59a-4fdd-b51c-4d2ac376ffb8.PNG">
Below macro 1 does not run
<img width="433" alt="9" src="https://user-images.githubusercontent.com/82966157/152199442-4b3c0983-339b-4a60-9a3a-59bb477e51d5.PNG">
Since this has now been unbound and cant be bound again, obviously it wont run. But before it was bound correctly, not sure what changed here as all i did was reboot for a new session.
<img width="907" alt="10" src="https://user-images.githubusercontent.com/82966157/152199637-6f8bfddf-514e-4e99-a440-0c208953c980.PNG">

I tried launching FF before Auto and vice versa.

**Comment by Saad888** [comment]
Thanks for the detailed images! As for the cancel being greyed out, it only lights up when food or syrup is selected as cancel isn't required unless those are active.

Could you by any chance try swapping the hotkeys off of F10 and onto anything else? I believe F10 has been causing issues for some people for some reason.

**Comment by vetox20** [comment]
Moving all keybinds away from the Function keys has resolved the issue. CTRL-Q for macro 1, Ctrl-W for macro 2, Ctrl-E for Confirm and it went like a charm. Also added a 3 second buffer from start of craft time. Thank you for the quick response!

**Comment by Saad888** [comment]
Glad to hear it! Yeah function keys seem to be causing some issues, I think
it has to do with steam overlay but not sure exactly

**Comment by vetox20** [comment]
just for your own knowledge this is with the non-steam version the issues were occurring as well
