### ISSUE TITLE
Refreshing syrup near targettable objects seems buggy

### ISSUE THREAD

**Issue by ghost** [Saad888/AutoSynthesis#3]
Hi! I think there's a bug when refreshing syrup (I haven't tested food but possibly could have the same problem). It seems that somehow AutoSynthesis was making me target NPCs or any targettable object near me before beginning the craft but _after_ refreshing the syrup, then this resulted in a state where AutoSynthesis would start the macro but there was no crafting window open. I fixed this problem by going to a very remote area with nothing targettable nearby and dismissing my pet, and the refresh worked fine like this.

**Comment by Saad888** [comment]
Hi Robert! Unfortunately, this is a known issue during development and I wasn't able to find a consistent resolution to this. Because of the way FFXIV handles controller inputs I have to send extra "Confirm" actions between initiating a craft and starting the macro. Under most conditions, this will result in an extra "confirm" being sent and if anything is targetable in the distance it will lock onto that and cancel the craft. Removing this extra craft though has a high chance of stopping the autocrafter from initiating the next craft altogether. 

Your best bet is when you're using food/pots with the autocrafter would be in an isolated area without anything targettable in the screen, like you did. Its a limitation I can't get around without directly injecting the app into FFXIV itself, and I don't plan on doing that with this app.
